// Fallback for the wasm-bindgen output normally generated by `npm run build:wasm` (requires Rust +
// wasm-pack). ensure-pkg.mjs copies it into WASM_FileProcessor/pkg/ whenever that toolchain is
// absent, so `npm run check` and `npm run build` still succeed. Every operation throws; callers
// already fall back to the pure TypeScript parser, see Processor.enableWasmProcessing / loadFile.
//
// The accompanying .d.ts is a verbatim copy of the generated one, refreshed by `npm run build:wasm`
// so the two cannot drift. This file stays generic to match: class members resolve through a Proxy
// instead of being listed, so an ABI change never needs an edit here

const NOT_BUILT_MESSAGE =
   'WASM G-code processor is not built. Run `npm run build:wasm` on a machine with Rust + wasm-pack installed, then rebuild.'

function unbuilt() {
   throw new Error(NOT_BUILT_MESSAGE)
}

function stubClass() {
   return new Proxy(class {}, {
      get(target, prop) {
         return typeof prop === 'symbol' || prop === 'name' || prop === 'prototype' ? Reflect.get(target, prop) : unbuilt
      },
      construct() {
         unbuilt()
      }
   })
}

export default async function init() {
   unbuilt()
}

export function initSync() {
   unbuilt()
}

export function main() {
   unbuilt()
}

export function get_version() {
   return 'unbuilt'
}

export const ProcessingResult = stubClass()
export const PositionData = stubClass()
export const RenderBuffers = stubClass()
export const GCodeProcessor = stubClass()
